### ISSUE TITLE
Move to rollkit organization

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/rollmint#659]
- [ ] Move rollmint to rollkit/rollkit
- [ ] Move iavl to rollkit/iavl
- [ ] Rename rollmint to rollkit in the code
- [ ] Create a fork of cosmos-sdk in rollkit/cosmos-sdk
- [ ] Transfer issues from cosmos-sdk-rollmint to rollkit/cosmos-sdk
- [ ] Fix imports in rollkit/cosmos-sdk
- [ ] Create a new project board in rollkit organization

**Comment by tzdybal** [comment]
Replaced by #697.
